### PR TITLE
Fix Detekt task classpath

### PR DESCRIPTION
**Pull request by cortinico**
This is a sample PR to verify a correct configuration of the Detekt classpath for Type Resolution (and to avoid false positives on `UnnecessarySafeCall`).

Feel free to disregard and incorporate the changes in a different way.

### CODE REVIEW

**Comment by cortinico** [comment]
See https://github.com/detekt/detekt/issues/3414 for reference

**Comment by Whathecode** [comment]
Thank you for all the information! Extremely informative and at a glance seems like it will fix the issues. I will definitely incorporate these changes later!

**Review by Whathecode — APPROVED** [review]

**Comment by Whathecode** [comment]
@cortinico Thank you again! I simply applied your changes in the main build file so that they work for all subprojects.

Looking forward to the next release so that I can remove the suppressed warnings for the `expect object` scenario (https://github.com/detekt/detekt/issues/3415). ;p

**Comment by cortinico** [comment]
Awesome 🙏

**Pull request merged**
