### PR TITLE
Add studyDeploymentId field to ParticipationAdded event

### PR DESCRIPTION
**Pull request by ltj**
We need to store the studyDeploymentId alongside study participations. This field was missing in `ParticipationAdded` event forcing a more complex repo implementation to search through the participations map in the study, rather than just getting it directly.

### CODE REVIEW

**Comment by ltj** [comment]
Thanks @Whathecode . I know it's tiny, but can we turn it into an alpha-16 release? Maybe with some small goodies you have lying around...or not :)

**Comment by Whathecode** [comment]
Can't you just use the snapshot release during development (on a new branch)? That's what it is there for.

**Comment by Whathecode** [comment]
Can't you just use the snapshot release during development (on a new branch)? That's what it is there for.

**Comment by ltj** [comment]
Yes! I forgot about the marvellous ci-cd setup

**Pull request merged**
