### PR TITLE
Implemented SmartphoneDeviceRegistration

### PR DESCRIPTION
**Pull request by bardram**

### CODE REVIEW

**Comment by bardram** [comment]
All the parameters that I can collect from a phone on Android / iOS (via the Flutter plugin) is now added to the SmartphoneRegistration.

**Comment by bardram** [comment]
I'm getting a unit test error that I don't understand - I can't even fint the test that is failing:

```
AssertionError: Serialization of type 'class Smartphone' failed.. Expected <Smartphone(roleName=User's phone, isOptional=false, defaultSamplingConfiguration={})>, actual <[object Object]>.
	at Object.captureStack(/var/folders/_p/g38r18fs3c19q8wnlys0f31c0000gq/T/_karma_webpack_548980/commons.js:86245)
	at AssertionError.constructor(/var/folders/_p/g38r18fs3c19q8wnlys0f31c0000gq/T/_karma_webpack_548980/commons.js:86553)
	at <global>.new AssertionError(/var/folders/_p/g38r18fs3c19q8wnlys0f31c0000gq/T/_karma_webpack_548980/commons.js:86750)
	at DefaultJsAsserter.assertTrue(/var/folders/_p/g38r18fs3c19q8wnlys0f31c0000gq/T/_karma_webpack_548980/commons.js:45919)
	at Asserter.assertEquals(/var/folders/_p/g38r18fs3c19q8wnlys0f31c0000gq/T/_karma_webpack_548980/commons.js:45712)
	at DefaultJsAsserter.assertEquals(/var/folders/_p/g38r18fs3c19q8wnlys0f31c0000gq/T/_karma_webpack_548980/commons.js:45890)
	at <global>.assertEquals(/var/folders/_p/g38r18fs3c19q8wnlys0f31c0000gq/T/_karma_webpack_548980/commons.js:45056)
	at ConcreteTypesSerializationTest.can_serialize_all_instances_using_JSON(/var/folders/_p/g38r18fs3c19q8wnlys0f31c0000gq/T/_karma_webpack_548980/commons.js:40330)
	at <global>.<unknown>(/var/folders/_p/g38r18fs3c19q8wnlys0f31c0000gq/T/_karma_webpack_548980/commons.js:23495)
	at Context.<anonymous>(/var/folders/_p/g38r18fs3c19q8wnlys0f31c0000gq/T/_karma_webpack_548980/commons.js:44874)
```

**Comment by Whathecode** [comment]
@bardram I think you are looking in the wrong location. [From the failing test run](https://github.com/cph-cachet/carp.core-kotlin/actions/runs/4161754236/jobs/7200103233):

```
> Task :rpc:test

dk.cachet.carp.rpc.JsonSchemasTest > schema_validation_for_generated_examples_succeeds FAILED
    com.networknt.schema.JsonSchemaException at JsonSchemasTest.kt:35
        Caused by: com.fasterxml.jackson.core.JsonParseException at JsonSchemasTest.kt:35
```

**Comment by Whathecode** [comment]
We determined that `SmartphoneDeviceRegistration` warrants more analysis, but it is very clear that device registrations should allow to add general freeform data (#431). Implementing that feature should to a large extend resolve this for now and takes priority over further analysis.

**Pull request closed without merging**
